import { ThemePack } from "./types";

export const THEME_PACKS: ThemePack[] = [
  {
    slug: "peak-fortune",
    name: "Peak Fortune",
    description: "PeakBet's flagship slot — climb the mountain to the ultimate jackpot.",
    gradient: ["#ffd700", "#8a7218"],
    volatility: "high",
    rtp: 96.8,
    hasJackpot: true,
    isFeatured: true,
    isPopular: true,
    lowIcons: ["🍀", "🔔", "⭐", "🃏"],
    midIcons: ["💰", "👑"],
    highIcons: ["💎", "🏔️"],
    wildIcon: "🔱",
    scatterIcon: "🏆",
  },
  {
    slug: "golden-pharaoh",
    name: "Golden Pharaoh",
    description: "Uncover the treasures buried deep in the pharaoh's tomb.",
    gradient: ["#ffd700", "#0d0d0f"],
    volatility: "high",
    rtp: 95.9,
    hasJackpot: true,
    isFeatured: true,
    lowIcons: ["🪲", "🐍", "📜", "🏺"],
    midIcons: ["🐫", "👁️"],
    highIcons: ["🗿", "👑"],
    wildIcon: "☀️",
    scatterIcon: "🔺",
  },
  {
    slug: "book-of-peak",
    name: "Book of Peak",
    description: "An ancient tome holds the key to expanding wilds and free spins.",
    gradient: ["#8a7218", "#080808"],
    volatility: "high",
    rtp: 95.5,
    isPopular: true,
    lowIcons: ["📖", "🕯️", "🗝️", "🪶"],
    midIcons: ["🦉", "⚱️"],
    highIcons: ["🐫", "🔺"],
    wildIcon: "📖",
    scatterIcon: "👁️",
  },
  {
    slug: "lucky-fruits",
    name: "Lucky Fruits",
    description: "The juiciest classic fruit machine on PeakBet.",
    gradient: ["#ff4d5e", "#39ff88"],
    volatility: "low",
    rtp: 97.4,
    lowIcons: ["🍒", "🍋", "🍇", "🍊"],
    midIcons: ["🍉", "🍓"],
    highIcons: ["🔔", "7️⃣"],
    wildIcon: "⭐",
    scatterIcon: "🍀",
  },
  {
    slug: "sweet-candy",
    name: "Sweet Candy",
    description: "A sugar rush of wilds, multipliers, and candy cascades.",
    gradient: ["#ff8fd6", "#b177ff"],
    volatility: "low",
    rtp: 97.1,
    lowIcons: ["🍬", "🍭", "🧁", "🍩"],
    midIcons: ["🍫", "🍪"],
    highIcons: ["🍰", "🎂"],
    wildIcon: "🌈",
    scatterIcon: "🍨",
  },
  {
    slug: "wild-wolf",
    name: "Wild Wolf",
    description: "Run with the pack across the moonlit plains for stacked wilds.",
    gradient: ["#8a7218", "#080808"],
    volatility: "high",
    rtp: 96.1,
    isPopular: true,
    lowIcons: ["🦅", "🐍", "🐎", "🦌"],
    midIcons: ["🦬", "🌵"],
    highIcons: ["🦁", "💰"],
    wildIcon: "🐺",
    scatterIcon: "🌕",
  },
  {
    slug: "buffalo-kingdom",
    name: "Buffalo Kingdom",
    description: "Stampede across the plains chasing a thundering jackpot.",
    gradient: ["#8a7218", "#ff4d5e"],
    volatility: "medium",
    rtp: 96.4,
    lowIcons: ["🦅", "🐍", "🐎", "🦌"],
    midIcons: ["🦬", "🌵"],
    highIcons: ["💰", "⭐"],
    wildIcon: "👑",
    scatterIcon: "⭐",
  },
  {
    slug: "pirate-treasure",
    name: "Pirate Treasure",
    description: "Set sail for sunken chests guarded by a ghostly captain.",
    gradient: ["#3ba7ff", "#080808"],
    volatility: "medium",
    rtp: 96.6,
    lowIcons: ["⚓", "🗡️", "🏴‍☠️", "🦜"],
    midIcons: ["💰", "🗺️"],
    highIcons: ["👑", "💎"],
    wildIcon: "☠️",
    scatterIcon: "🏝️",
  },
  {
    slug: "mystic-forest",
    name: "Mystic Forest",
    description: "Fireflies light the way to a hidden unicorn glade.",
    gradient: ["#39ff88", "#b177ff"],
    volatility: "medium",
    rtp: 96.9,
    lowIcons: ["🍄", "🦋", "🌿", "🦉"],
    midIcons: ["🧚", "🌙"],
    highIcons: ["🦄", "🌳"],
    wildIcon: "✨",
    scatterIcon: "🔮",
  },
  {
    slug: "olympus-gods",
    name: "Olympus Gods",
    description: "Call down lightning from the throne of the gods.",
    gradient: ["#3ba7ff", "#ffd700"],
    volatility: "high",
    rtp: 95.7,
    hasJackpot: true,
    isFeatured: true,
    lowIcons: ["🏛️", "🗡️", "🛡️", "🕊️"],
    midIcons: ["🦅", "🔱"],
    highIcons: ["👑", "🦁"],
    wildIcon: "⚡",
    scatterIcon: "🏛️",
  },
  {
    slug: "ancient-egypt",
    name: "Ancient Egypt",
    description: "Walk the Nile past temples stacked with expanding symbols.",
    gradient: ["#ffd700", "#3ba7ff"],
    volatility: "medium",
    rtp: 96.5,
    lowIcons: ["🪲", "🐍", "📜", "🥻"],
    midIcons: ["🐫", "🔺"],
    highIcons: ["👁️", "👑"],
    wildIcon: "☥",
    scatterIcon: "🗿",
  },
  {
    slug: "magic-lamp",
    name: "Magic Lamp",
    description: "Rub the lamp for three free-spin wishes and a genie multiplier.",
    gradient: ["#b177ff", "#ffd700"],
    volatility: "medium",
    rtp: 96.7,
    lowIcons: ["🕯️", "📜", "🗝️", "💍"],
    midIcons: ["🪔", "🕌"],
    highIcons: ["💎", "👑"],
    wildIcon: "🧞",
    scatterIcon: "✨",
  },
  {
    slug: "lucky-sevens",
    name: "Lucky Sevens",
    description: "No frills, just bars, bells, and stacks of golden sevens.",
    gradient: ["#ff4d5e", "#ffd700"],
    volatility: "low",
    rtp: 97.6,
    lowIcons: ["🍒", "🍋", "🔔", "🍇"],
    midIcons: ["💎", "⭐"],
    highIcons: ["7️⃣", "💰"],
    wildIcon: "🎰",
    scatterIcon: "🍀",
  },
  {
    slug: "diamond-rush",
    name: "Diamond Rush",
    description: "A dazzling vault of diamonds with a shot at the mega jackpot.",
    gradient: ["#3ba7ff", "#ffffff"],
    volatility: "high",
    rtp: 95.6,
    hasJackpot: true,
    lowIcons: ["💍", "🔷", "⚪", "🔘"],
    midIcons: ["💠", "🔶"],
    highIcons: ["💎", "👑"],
    wildIcon: "✨",
    scatterIcon: "🌟",
  },
  {
    slug: "fire-phoenix",
    name: "Fire Phoenix",
    description: "Rise from the ashes with blazing multipliers on every respin.",
    gradient: ["#ff4d5e", "#ffd700"],
    volatility: "high",
    rtp: 95.8,
    hasJackpot: true,
    isFeatured: true,
    lowIcons: ["🔥", "🪶", "⭐", "🌋"],
    midIcons: ["🦅", "☄️"],
    highIcons: ["🐦‍🔥", "👑"],
    wildIcon: "🔥",
    scatterIcon: "💥",
  },
  {
    slug: "dragon-empire",
    name: "Dragon Empire",
    description: "An imperial dragon guards free spins behind the palace gates.",
    gradient: ["#ff4d5e", "#080808"],
    volatility: "high",
    rtp: 96.0,
    lowIcons: ["⚔️", "🏯", "🥋", "🎋"],
    midIcons: ["🐲", "🔥"],
    highIcons: ["👑", "💰"],
    wildIcon: "🐉",
    scatterIcon: "⛩️",
  },
  {
    slug: "frozen-kingdom",
    name: "Frozen Kingdom",
    description: "An icy palace where snowfall wilds cascade down the reels.",
    gradient: ["#3ba7ff", "#ffffff"],
    volatility: "medium",
    rtp: 96.6,
    lowIcons: ["❄️", "🧊", "🦌", "🐧"],
    midIcons: ["⛄", "🌨️"],
    highIcons: ["👑", "💎"],
    wildIcon: "🥶",
    scatterIcon: "❄️",
  },
  {
    slug: "wild-west",
    name: "Wild West",
    description: "Duel for the jackpot at high noon in a dusty frontier town.",
    gradient: ["#8a7218", "#ff4d5e"],
    volatility: "medium",
    rtp: 96.3,
    lowIcons: ["🌵", "🐎", "🔫", "🥃"],
    midIcons: ["🤠", "🐂"],
    highIcons: ["💰", "👑"],
    wildIcon: "⭐",
    scatterIcon: "🏜️",
  },
  {
    slug: "big-bass-bounty",
    name: "Big Bass Bounty",
    description: "Reel in the big one for a bonus round full of wild catches.",
    gradient: ["#3ba7ff", "#39ff88"],
    volatility: "high",
    rtp: 96.2,
    isPopular: true,
    lowIcons: ["🪱", "⚓", "🥤", "🦆"],
    midIcons: ["🐟", "🚤"],
    highIcons: ["🐠", "💰"],
    wildIcon: "🎣",
    scatterIcon: "💧",
  },
  {
    slug: "jungle-adventure",
    name: "Jungle Adventure",
    description: "Swing through the canopy chasing a lost temple's riches.",
    gradient: ["#39ff88", "#8a7218"],
    volatility: "medium",
    rtp: 96.5,
    lowIcons: ["🍌", "🦜", "🌴", "🥥"],
    midIcons: ["🐒", "🐆"],
    highIcons: ["🦍", "💎"],
    wildIcon: "🌟",
    scatterIcon: "🗿",
  },
  {
    slug: "zombie-escape",
    name: "Zombie Escape",
    description: "Survive the outbreak for a chance at the last-stand jackpot.",
    gradient: ["#39ff88", "#080808"],
    volatility: "high",
    rtp: 95.9,
    lowIcons: ["🦴", "🪓", "🔦", "🩹"],
    midIcons: ["💀", "🧠"],
    highIcons: ["⚰️", "🩸"],
    wildIcon: "🧟",
    scatterIcon: "🌕",
  },
  {
    slug: "samurai-honor",
    name: "Samurai Honor",
    description: "One blade, one strike — trigger the honor bonus round.",
    gradient: ["#ff4d5e", "#080808"],
    volatility: "medium",
    rtp: 96.4,
    lowIcons: ["🗡️", "⛩️", "🏮", "🎋"],
    midIcons: ["🥋", "🐉"],
    highIcons: ["👺", "👑"],
    wildIcon: "⚔️",
    scatterIcon: "🏯",
  },
  {
    slug: "ninja-gold",
    name: "Ninja Gold",
    description: "Strike from the shadows for stacked gold multipliers.",
    gradient: ["#ffd700", "#080808"],
    volatility: "high",
    rtp: 96.0,
    lowIcons: ["🗡️", "⭐", "🌑", "🎯"],
    midIcons: ["🏹", "🌙"],
    highIcons: ["💰", "👑"],
    wildIcon: "🥷",
    scatterIcon: "🔔",
  },
  {
    slug: "vampire-castle",
    name: "Vampire Castle",
    description: "Enter the castle at midnight for a blood-moon bonus.",
    gradient: ["#ff4d5e", "#080808"],
    volatility: "high",
    rtp: 95.8,
    lowIcons: ["🦇", "🕸️", "🩸", "🗝️"],
    midIcons: ["🧛", "🏰"],
    highIcons: ["👑", "💍"],
    wildIcon: "🌹",
    scatterIcon: "🌕",
  },
  {
    slug: "candy-explosion",
    name: "Candy Explosion",
    description: "Cascading candies explode into ever-growing multipliers.",
    gradient: ["#ff4d5e", "#b177ff"],
    volatility: "low",
    rtp: 97.2,
    lowIcons: ["🍬", "🍭", "🍩", "🧁"],
    midIcons: ["🍫", "🎂"],
    highIcons: ["🍓", "💥"],
    wildIcon: "🌈",
    scatterIcon: "🍨",
  },
  {
    slug: "neon-vegas",
    name: "Neon Vegas",
    description: "The strip at 2am — bright lights, big multipliers.",
    gradient: ["#b177ff", "#39ff88"],
    volatility: "medium",
    rtp: 96.8,
    isFeatured: true,
    isPopular: true,
    lowIcons: ["🎰", "🃏", "🔔", "🍒"],
    midIcons: ["💃", "🎷"],
    highIcons: ["💎", "👑"],
    wildIcon: "✨",
    scatterIcon: "🌃",
  },
  {
    slug: "treasure-hunter",
    name: "Treasure Hunter",
    description: "Follow the map to a chest sealed with an ancient jackpot.",
    gradient: ["#8a7218", "#ffd700"],
    volatility: "medium",
    rtp: 96.5,
    lowIcons: ["🗺️", "🧭", "🔦", "⛏️"],
    midIcons: ["💰", "🗝️"],
    highIcons: ["💎", "👑"],
    wildIcon: "🏺",
    scatterIcon: "⛰️",
  },
  {
    slug: "mega-fruits",
    name: "Mega Fruits",
    description: "Fruit machine classics, supersized with mega multiplier wilds.",
    gradient: ["#39ff88", "#ffd700"],
    volatility: "medium",
    rtp: 96.9,
    lowIcons: ["🍒", "🍋", "🍉", "🍇"],
    midIcons: ["🍓", "🍍"],
    highIcons: ["🔔", "7️⃣"],
    wildIcon: "⭐",
    scatterIcon: "🍀",
  },
  {
    slug: "lucky-panda",
    name: "Lucky Panda",
    description: "Red envelopes rain down in this festival of fortune.",
    gradient: ["#ff4d5e", "#39ff88"],
    volatility: "low",
    rtp: 97.3,
    isPopular: true,
    lowIcons: ["🎋", "🏮", "🍵", "🌸"],
    midIcons: ["🐼", "🧧"],
    highIcons: ["💰", "👑"],
    wildIcon: "🎍",
    scatterIcon: "🔔",
  },
  {
    slug: "aztec-riches",
    name: "Aztec Riches",
    description: "Ancient stone gates open onto a sun-god jackpot chamber.",
    gradient: ["#ffd700", "#ff4d5e"],
    volatility: "high",
    rtp: 95.7,
    hasJackpot: true,
    lowIcons: ["🌽", "🦅", "🪶", "🏺"],
    midIcons: ["🐍", "🔺"],
    highIcons: ["💰", "👑"],
    wildIcon: "🗿",
    scatterIcon: "🌞",
  },
  {
    slug: "christmas-magic",
    name: "Christmas Magic",
    description: "Unwrap free spins under the tree this holiday season.",
    gradient: ["#ff4d5e", "#39ff88"],
    volatility: "low",
    rtp: 97.0,
    isNew: true,
    lowIcons: ["🎄", "🔔", "⭐", "🍬"],
    midIcons: ["🎁", "⛄"],
    highIcons: ["🎅", "👑"],
    wildIcon: "❄️",
    scatterIcon: "✨",
  },
  {
    slug: "halloween-night",
    name: "Halloween Night",
    description: "Trick-or-treat your way to a spooky multiplier round.",
    gradient: ["#8a7218", "#080808"],
    volatility: "high",
    rtp: 95.9,
    isNew: true,
    lowIcons: ["🎃", "🦇", "🕸️", "👻"],
    midIcons: ["🧙", "🍬"],
    highIcons: ["💀", "👑"],
    wildIcon: "🌕",
    scatterIcon: "🕯️",
  },
  {
    slug: "space-galaxy",
    name: "Space Galaxy",
    description: "Blast off past the asteroid belt for a cosmic jackpot.",
    gradient: ["#3ba7ff", "#b177ff"],
    volatility: "high",
    rtp: 96.1,
    isNew: true,
    isFeatured: true,
    lowIcons: ["⭐", "🪐", "☄️", "🛰️"],
    midIcons: ["👽", "🚀"],
    highIcons: ["💎", "👑"],
    wildIcon: "🛸",
    scatterIcon: "🌌",
  },
  {
    slug: "cyber-spin",
    name: "Cyber Spin",
    description: "Hack the mainframe for a glitch-multiplier free spin round.",
    gradient: ["#39ff88", "#080808"],
    volatility: "high",
    rtp: 95.8,
    isNew: true,
    lowIcons: ["💾", "🔌", "📟", "🔋"],
    midIcons: ["🤖", "💻"],
    highIcons: ["💎", "👑"],
    wildIcon: "⚡",
    scatterIcon: "🛰️",
  },
  {
    slug: "retro-777",
    name: "Retro 777",
    description: "The original one-arm bandit, digitized for PeakBet.",
    gradient: ["#ff4d5e", "#ffd700"],
    volatility: "low",
    rtp: 97.5,
    lowIcons: ["🍒", "🍋", "🔔", "🍇"],
    midIcons: ["💰", "⭐"],
    highIcons: ["7️⃣", "💎"],
    wildIcon: "🎰",
    scatterIcon: "🍀",
  },
  {
    slug: "golden-crown",
    name: "Golden Crown",
    description: "Only royalty reaches the crown jewel jackpot round.",
    gradient: ["#ffd700", "#ffffff"],
    volatility: "high",
    rtp: 95.6,
    hasJackpot: true,
    isFeatured: true,
    lowIcons: ["💍", "⭐", "🔔", "🍀"],
    midIcons: ["💰", "💎"],
    highIcons: ["👑", "🏆"],
    wildIcon: "✨",
    scatterIcon: "🎖️",
  },
];
