import { GameMeta } from "./types";

/** Every non-slot game: table classics, instant/crash-style games, and card games. */
export const TABLE_GAMES: GameMeta[] = [
  {
    slug: "crash",
    name: "Crash",
    category: "instant",
    description: "Watch the multiplier climb and cash out before it crashes.",
    rtp: 99,
    volatility: "high",
    minBet: 1,
    maxBet: 5000,
    isFeatured: true,
    isPopular: true,
    icon: "🚀",
    gradient: ["#ff4d5e", "#39ff88"],
  },
  {
    slug: "dice",
    name: "Dice",
    category: "instant",
    description: "Roll under or over your target — pick your own risk.",
    rtp: 99,
    volatility: "medium",
    minBet: 1,
    maxBet: 5000,
    isPopular: true,
    icon: "🎲",
    gradient: ["#ffd700", "#8a7218"],
  },
  {
    slug: "coinflip",
    name: "Coin Flip",
    category: "instant",
    description: "Heads or tails. Double or nothing, the classic way.",
    rtp: 98,
    volatility: "medium",
    minBet: 1,
    maxBet: 5000,
    icon: "🪙",
    gradient: ["#ffd700", "#fff3b0"],
  },
  {
    slug: "mines",
    name: "Mines",
    category: "instant",
    description: "Reveal gems, avoid the mines, cash out anytime.",
    rtp: 98,
    volatility: "high",
    minBet: 1,
    maxBet: 5000,
    isFeatured: true,
    isPopular: true,
    icon: "💣",
    gradient: ["#3ba7ff", "#080808"],
  },
  {
    slug: "plinko",
    name: "Plinko",
    category: "instant",
    description: "Drop the ball, watch it bounce through the pegs.",
    rtp: 98,
    volatility: "high",
    minBet: 1,
    maxBet: 5000,
    isPopular: true,
    icon: "⚪",
    gradient: ["#b177ff", "#3ba7ff"],
  },
  {
    slug: "keno",
    name: "Keno",
    category: "instant",
    description: "Pick your lucky numbers, match the draw.",
    rtp: 96,
    volatility: "medium",
    minBet: 1,
    maxBet: 2000,
    icon: "🔢",
    gradient: ["#39ff88", "#0dff9c"],
  },
  {
    slug: "wheel",
    name: "Wheel",
    category: "instant",
    subcategory: "Lucky Wheel",
    description: "Spin the wheel of fortune for instant multipliers.",
    rtp: 97,
    volatility: "medium",
    minBet: 1,
    maxBet: 3000,
    icon: "🎡",
    gradient: ["#ffd700", "#ff4d5e"],
  },
  {
    slug: "hilo",
    name: "Hi-Lo",
    category: "cards",
    description: "Guess if the next card is higher or lower.",
    rtp: 97,
    volatility: "medium",
    minBet: 1,
    maxBet: 3000,
    icon: "🃏",
    gradient: ["#3ba7ff", "#b177ff"],
  },
  {
    slug: "dragon-tower",
    name: "Dragon Tower",
    category: "instant",
    description: "Climb the tower one level at a time. One wrong step ends it.",
    rtp: 97,
    volatility: "high",
    minBet: 1,
    maxBet: 3000,
    icon: "🐉",
    gradient: ["#ff4d5e", "#ffd700"],
  },
  {
    slug: "limbo",
    name: "Limbo",
    category: "instant",
    description: "Set a target multiplier and see how high the number goes.",
    rtp: 99,
    volatility: "high",
    minBet: 1,
    maxBet: 5000,
    icon: "📈",
    gradient: ["#39ff88", "#3ba7ff"],
  },
  {
    slug: "rock-paper-scissors",
    name: "Rock Paper Scissors",
    category: "instant",
    description: "Beat the house AI in the oldest game there is.",
    rtp: 97,
    volatility: "low",
    minBet: 1,
    maxBet: 2000,
    icon: "✊",
    gradient: ["#9a9aa2", "#ffd700"],
  },
  {
    slug: "number-guess",
    name: "Number Guess",
    category: "instant",
    description: "Guess the number between 1 and 100. Closer bets pay more.",
    rtp: 96,
    volatility: "medium",
    minBet: 1,
    maxBet: 2000,
    icon: "🔮",
    gradient: ["#b177ff", "#ffd700"],
  },
  {
    slug: "european-roulette",
    name: "European Roulette",
    category: "table",
    description: "Single-zero roulette. The classic European wheel.",
    rtp: 97.3,
    volatility: "medium",
    minBet: 1,
    maxBet: 5000,
    isFeatured: true,
    icon: "🎯",
    gradient: ["#ff4d5e", "#080808"],
  },
  {
    slug: "american-roulette",
    name: "American Roulette",
    category: "table",
    description: "Double-zero roulette with the full American layout.",
    rtp: 94.7,
    volatility: "medium",
    minBet: 1,
    maxBet: 5000,
    icon: "🎯",
    gradient: ["#ffd700", "#ff4d5e"],
  },
  {
    slug: "blackjack",
    name: "Blackjack",
    category: "cards",
    description: "Beat the dealer to 21 without going bust.",
    rtp: 99.3,
    volatility: "low",
    minBet: 1,
    maxBet: 5000,
    isFeatured: true,
    isPopular: true,
    icon: "♠️",
    gradient: ["#080808", "#39ff88"],
  },
  {
    slug: "baccarat",
    name: "Baccarat",
    category: "cards",
    description: "Bet on Player, Banker, or Tie in this timeless classic.",
    rtp: 98.9,
    volatility: "low",
    minBet: 1,
    maxBet: 5000,
    icon: "♦️",
    gradient: ["#ff4d5e", "#ffd700"],
  },
  {
    slug: "video-poker",
    name: "Video Poker",
    category: "cards",
    subcategory: "Jacks or Better",
    description: "Hold your best cards, draw the rest, chase a royal flush.",
    rtp: 99.5,
    volatility: "medium",
    minBet: 1,
    maxBet: 2000,
    icon: "🂡",
    gradient: ["#3ba7ff", "#ffd700"],
  },
  {
    slug: "five-card-poker",
    name: "Poker",
    category: "cards",
    subcategory: "5-Card Draw",
    description: "Classic five-card draw against the house paytable.",
    rtp: 97.8,
    volatility: "medium",
    minBet: 1,
    maxBet: 2000,
    icon: "🂮",
    gradient: ["#b177ff", "#080808"],
  },
  {
    slug: "texas-holdem",
    name: "Texas Hold'em Demo",
    category: "cards",
    description: "Heads-up Texas Hold'em against the PeakBet dealer bot.",
    rtp: 97.5,
    volatility: "medium",
    minBet: 5,
    maxBet: 2000,
    isNew: true,
    icon: "🂠",
    gradient: ["#39ff88", "#080808"],
  },
];
